sync:
  groups:
    employee:
      - CN=biolaemployees,OU=Biola Security Groups,DC=adtest,DC=biola,DC=edu
    # This should be uncommented when the faculty emeritus affiliation is in trogdir
    # faculty emeritus:
    #   - CN=biolafacultyemeriti,OU=Biola Security Groups,DC=adtest,DC=biola,DC=edu
    student:
      - CN=biolastudents,OU=Biola Security Groups,DC=adtest,DC=biola,DC=edu
    student worker:
      - CN=biolastudentworkers,OU=Biola Security Groups,DC=adtest,DC=biola,DC=edu
    trustee:
      - CN=biolatrustees,OU=Biola Security Groups,DC=adtest,DC=biola,DC=edu
